In [1]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(s)

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
})
print(df)

In [3]:
df = pd.read_csv('Data/Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

## Data Selection

In [ ]:

df[["Id", "SepalLengthCm"]]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [11]:
type(df["Id"])

pandas.Series

In [12]:
df.iloc[0]  # First row

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [13]:
df.iloc[1:4]  # Rows 1 to 3

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa

In [14]:
df.dropna(inplace=True) # Drop rows with missing values ,inplace=True changes the original DataFrame, if inplace=False it returns a new DataFrame with the rows dropped

In [ ]:
df.fillna(method='ffill', inplace=True) # Fill missing values method='ffill' fills the missing values with the last valid observation

In [20]:
df.rename(columns={'Id': 'ID', "SepalLengthCm": "SC"})

      ID   SC  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [23]:
df['SepalLengthCm'] = df['SepalLengthCm'].astype(float)  # Convert to float

In [24]:
df["new_col"] = [0 for i in range(len(df))]  # Add a new column with default value 0

In [25]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,new_col
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,0
146,147,6.3,2.5,5.0,1.9,Iris-virginica,0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,0

In [26]:
df.to_csv('Data/Iris_modified.csv', index=False) # Save the modified DataFrame to a new CSV file without the index

In [31]:
df1 = pd.DataFrame({
    'Name': ['David', 'Eve'],
    'Age': [28, 22],
    'City': ['Miami', 'Seattle']
})
print(df1)

    Name  Age     City
0  David   28    Miami
1    Eve   22  Seattle

In [32]:
df2 = pd.DataFrame({
    'Name': ['Frank', 'Grace'], 
    'Age': [33, 27],
    'City': ['Austin', 'Denver']
})
print(df2)

    Name  Age    City
0  Frank   33  Austin
1  Grace   27  Denver

In [30]:
df3 = pd.concat([df1, df2], ignore_index=True)  # Concatenate DataFrames and reset index
print(df3)

    Name  Age     City
0  David   28    Miami
1    Eve   22  Seattle
2  Frank   33   Austin
3  Grace   27   Denver

In [33]:
d4 = pd.merge(df1, df2, on='Name', how='inner')  # Merge DataFrames on 'Name' column using inner join
print(d4)

Empty DataFrame
Columns: [Name, Age_x, City_x, Age_y, City_y]
Index: []